# docker-compose.yml

version: '3.8'
name: boilerplate
services:
  postgres:
    container_name: 'postgres-boilerplate'
    image: postgres:13.5
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: